-- New table specifically for SEC filing FULL TEXT
-- Separate from RAW_SEC_FILINGS which stores structured metrics

CREATE TABLE IF NOT EXISTS RAW.RAW_SEC_FILING_TEXT (
    TICKER VARCHAR(10) NOT NULL,
    CIK VARCHAR(10),
    COMPANY_NAME VARCHAR(200),
    FORM_TYPE VARCHAR(10) NOT NULL,
    FILING_DATE DATE NOT NULL,
    REPORT_DATE DATE,
    FISCAL_YEAR NUMBER(38,0),
    FISCAL_PERIOD VARCHAR(10),
    ACCESSION_NUMBER VARCHAR(30) NOT NULL,
    PRIMARY_DOCUMENT VARCHAR(200),
    FILING_TEXT VARIANT,
    FILING_URL VARCHAR(500),
    SOURCE VARCHAR(50) DEFAULT 'sec_edgar',
    INGESTED_AT TIMESTAMP_NTZ(9),
    DATA_QUALITY_SCORE FLOAT DEFAULT 100.0,
    PRIMARY KEY (TICKER, ACCESSION_NUMBER)
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_sec_text_ticker_date
ON RAW.RAW_SEC_FILING_TEXT(TICKER, FILING_DATE);

-- Index for LLM queries (get latest by type)
CREATE INDEX IF NOT EXISTS idx_sec_text_form_date
ON RAW.RAW_SEC_FILING_TEXT(TICKER, FORM_TYPE, FILING_DATE);

-- Add comment
COMMENT ON TABLE RAW.RAW_SEC_FILING_TEXT IS
'Full text of SEC 10-K and 10-Q filings for LLM analysis. Separate from RAW_SEC_FILINGS which stores structured XBRL metrics.';